### ISSUE TITLE
Error for the https://contracts-ui.substrate.io//

### ISSUE THREAD

**Issue by blue-freedom-technologies** [use-ink/contracts-ui#559]
**Describe the bug**

I have used the [flipper](https://github.com/paritytech/ink-examples/tree/main/flipper) example.

![image](https://github.com/use-ink/contracts-ui/assets/142290531/b1b3da91-81f1-4830-976b-5c23ab1e296b)

But the [contracts-ui](https://contracts-ui.substrate.io/) gives this error with no more explanations went we try to instantiate the contract.
![image](https://github.com/use-ink/contracts-ui/assets/142290531/7276021e-3ef5-4b42-a8a4-449c32b0fe26)

Note: using the cmd cargo contract instantiate --manifest-path=Cargo.toml --suri "***" -x --args true --url wss://rococo-contracts-rpc.polkadot.io it work as a charm.

**To Reproduce**

1. Upload the contract via the [contracts-ui](https://contracts-ui.substrate.io/)
2. Instantiate the contract
4. Error

**Expected behavior**
Be able to instancite the conctarto via the [contracts-ui](https://contracts-ui.substrate.io/) like we are able to do via the cmd "cargo contract instantiate --manifest-path=Cargo.toml --suri "***" -x --args true --url wss://rococo-contracts-rpc.polkadot.io"

**Screenshots**
![image](https://github.com/use-ink/contracts-ui/assets/142290531/7276021e-3ef5-4b42-a8a4-449c32b0fe26)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04.4 LTS
- Browser: firefox
- Version :125.0.2 (64-bit)

**Environment (please complete the following information where it makes sense):**

- contract version: ink! 5.0
- cargo-contract version: cargo-contract-contract 4.1.1-unknown-x86_64-unknown-linux-gnu
- chain name or dev node version wss://rococo-contracts-rpc.polkadot.io
- rust toolchain nightly-x86_64-unknown-linux-gnu (default)
- rustc version rustc 1.79.0-nightly (dbce3b43b 2024-04-20)

**Additional context**

[source code](https://github.com/blue-freedom-technologies/flipper)

**Comment by peetzweg** [comment]
Fixed by #560
